image:
  repository: truecharts/sonarr
  pullPolicy: IfNotPresent
  tag: latest

service:
  main:
    ports:
      main:
        port: 8989
        targetPort: 8989

probes:
  liveness:
    enabled: true
    ## Set this to true if you wish to specify your own livenessProbe
    custom: true
    ## The spec field contains the values for the default livenessProbe.
    ## If you selected custom: true, this field holds the definition of the livenessProbe.
    spec:
      exec:
        command:
          - /usr/bin/env
          - bash
          - -c
          - curl --fail localhost:8989/api/v3/system/status?apiKey=`IFS=\> && while
            read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
      failureThreshold: 5
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
